apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: student-app
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  nodePort: 30080